### ISSUE TITLE
請求入力：既存の見積りを再保存すると、支払予定日が未定になってしまう

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#156]
**Describe the bug**
既存の見積りを開き、再度保存をすると、支払予定日が見た目上入力されていても未定に変更されてしまう

**To Reproduce**
1. Go to 請求入力
2. 支払予定日が設定されている、既存の見積りを開く or 見積もりを作成する
3. 保存ボタンを押す
4. 保存後の画面で支払予定日が未定になる
5. See error

**Expected behavior**
検討中

**Comment by RPA02coco** [comment]
projInvoice\api\convertToKintone.ts内、```toKintoneDateStr(plannedPaymentDate)```にて```isTypeOfDate```の判定に失敗していることが原因でした。
ただし、見た目上渡しているデータに差異がない為、引き続き原因確認します。

**Comment by Lorenzras** [comment]
バグ確認しました。

日付を変えて、すぐ保存すると通常ですが、変えずにもう一回保存すると、未定になります。

plannedPaymentDate のタイプはどこかで Date Object型 → string  に変換されています。

`toKintoneDateStr` のJSDocの@todoに書かれているように、`string` は未対応なので、必要に応じて更新が必要です。💦
当時、Kintoneからの日付はDate型に変換して、そのまま、操作していたので怠けていました。笑

**Comment by RPA02coco** [comment]
#171 にて対応完了とします。
