### ISSUE TITLE
請求入力で、契約を選択していない状態でも保存ができてしまう

### ISSUE THREAD

**Issue by YokoHayakawa** [Lorenzras/yumecoco-monorepo#174]
**Describe the bug**
請求入力画面で、契約が存在しない場合や、選択していない場合でも請求書の保存・発行ができてしまう

**To Reproduce**
1. Go to https://rdmuhwtt6gx7.cybozu.com/k/176/#/project/payment/invoice
2. 契約が存在しない顧客を選択
3. Click on '保存' or '請求書発行'
　→　処理が進んでしまう

**Expected behavior**
 - バリデーション修正：契約書の選択が0の時は保存ボタン・請求書発行ボタンは無効
 - バリデーションが成功したときのみ、請求書のステータスを変更する
 - 契約が存在しない場合は、表示画面を変更する：ex.)まだ契約が存在しません
 　　　→見積りor契約画面への遷移を薦めるメッセージボックスorモーダルの表示 等

**Comment by Lorenzras** [comment]
Keep this issue alive.
