### ISSUE TITLE
見積もり登録画面で、ショートカットキーを追加してほしい

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#183]
**機能のリクエスト**

 - 見積もり画面で、前システムと同様のショートカットキーを追加してほしい

**実装案**

 前システムでは、以下のショートカットが実装されているため、同様もしくは同等のことができるようにしたいとのこと
 - [F7] : 1行上をコピー(複製)
 - [F10] : クリア

**代替案の説明**

 - 必ずしもファンクションキーに割り当てなくてよいと思います
 - ほとんどの機能(削除、追加等)は実装できているため、上記2つのみで使用感に対する抵抗は減らせるかと思います
 - ショートカットキーで操作できることを分かりやすく表示する必要があると感じました
 　ex.)ツールチップをヘッダとして固定する、最初数秒はマウスオーバーしてなくても表示しておく

**Comment by Lorenzras** [comment]
機能のリクエストの投稿ありがとうございます。

高橋さんに確認したところ、優先ではないので後回しでもよさそうです。
ただ、リクエストはどうなったか気になると思うので、どう伝えるか悩んでいます。

ユーザからリクエスト・提案の進歩はみんなで確認出来る体制が必要になるかもしれません。

AIによる：

[F7]と[F10]を使うこともできますが、ブラウザやOSによっては既に他の用途に割り当てられている可能性があります 。例えば、WindowsではF7はスペルチェック、F10はメニューバーの切り替えに使われています。そのため、ユーザーにとって混乱や不便を招かないように、注意深く選択する必要があります。また、ユーザーにファンクションキーの機能を明示的に教える方法も考える必要があります。😊
https://sl.bing.net/bapazWYWAtE

[F7]と[F10]を使うこともできますが、ブラウザやOSによっては既に他の用途に割り当てられている可能性があります 。例えば、WindowsではF7はスペルチェック、F10はメニューバーの切り替えに使われています。そのため、ユーザーにとって混乱や不便を招かないように、注意深く選択する必要があります。また、ユーザーにファンクションキーの機能を明示的に教える方法も考える必要があります。😊
https://sl.bing.net/fvm4S8YTUDk

**Comment by Lorenzras** [comment]
対応済みなので、クロースをさていただきます。
