### ISSUE TITLE
契約印刷画面で、見積り選択後に[----]を選択すると顧客情報がリセットされてしまう

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#187]
**Describe the bug**
---

 - 契約を印刷するの画面で、見積りが選択されている状態から、[見積選択]欄を[----]に変更するとバグになる

バグ内容
 - [工事情報の検索]では見た目上工事が選択されたままだが、画面上の顧客工事情報がクリアされる 
 - [見積選択]欄が[----]と[見積作成]の2メニューのみになってしまう

**To Reproduce**
---

1. 契約印刷画面へ移動 'https://rdmuhwtt6gx7.cybozu.com/k/176/#/project/contract/preview'
2. [工事情報の検索]欄で、適当な工事を選択する -> 顧客の工事の情報が表示される
3. [見積選択]欄で、適当な見積もりを選択する -> 選択した見積もり情報が表示される
5. [見積選択]欄で、[----]を選択する
7. See error

**Expected behavior**
---

見積選択で[----]を選択した際、上記2の状態になるように修正する
見積もりの変更に関わらず工事情報を保持する

**Comment by Lorenzras** [comment]
対応済みなので、クロースさせていただきます。
