### ISSUE TITLE
契約を印刷：金額にマイナス値が入力できない

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#62]
**Describe the bug**
対象のメニュー：契約を印刷
対象の入力フィールド：契約金、着工金(現．着手金)、中間金、最終金
現象：マイナスの値が入力できない

**To Reproduce**
1. Go to '契約を印刷'
2. 工事と見積りを選択する
3. 契約金額の入力欄で、マイナスの値を入力する

**Expected behavior**
追加減額の際には、マイナス(返金)の見積り及び契約が作成されるため、マイナス値での契約も発生します。

**Comment by Lorenzras** [comment]
対応します！
