### ISSUE TITLE
工事情報登録画面で、顧客が変更されたときに工事情報もクリアする

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#8]
**Is your feature request related to a problem? Please describe.**
工事情報登録画面の顧客検索フィールドで顧客情報が変更されたとき、工事場所情報が保持されている。
新規検索の際には問題ないが、1度検索・登録等の動作をしてから顧客を変更すると、
工事場所情報が残ってしまい、顧客と工事の紐づけが変更できるようになってしまっている。

**Describe the solution you'd like**

- 顧客が変更されたら、工事情報等をリフレッシュする
- 顧客検索フィールドの横に工事選択ボタンを設置し、既存の工事を編集できるようにする

**Describe alternatives you've considered**
見積もりと同様の構成に変更することで、顧客と工事の紐づけは変更できないようにする
既存の工事編集の選択が明確になるため、紐付けや設定のミスが減ると思われる

**Comment by Lorenzras** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [工事情報登録画面の改修](https://trello.com/c/PJrEqhGx/171-%E5%B7%A5%E4%BA%8B%E6%83%85%E5%A0%B1%E7%99%BB%E9%8C%B2%E7%94%BB%E9%9D%A2%E3%81%AE%E6%94%B9%E4%BF%AE)

**Comment by Lorenzras** [comment]
#17 で対応してマージしました。
