### ISSUE TITLE
円マークがバックスラッシュで表示されてしまう

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#88]
**現象**
大黒の見積りを読み込んだ際、備考欄で「定価　&yen;245,700-」等と記載している場合、&yen; が \ で表示されてしまいます。
日本語特有の問題だとは思いますが、解消しておいた方が良いかと思います。

**解消案**
```\```(バックスラッシュ)を```&yen;```に置き換える

**Comment by Lorenzras** [comment]
修正するPRがマージされましたので、クロースさせて頂きます。
