### ISSUE TITLE
大黒の原価明細読み込みの際、数量が0の物は単価も0円になってしまう

### ISSUE THREAD

**Issue by RPA02coco** [Lorenzras/yumecoco-monorepo#93]
**Describe the bug**
大黒の明細で、数量が0の部材の単価がすべて0になってしまう。
大黒の原価明細を読み込む際に起こる。通常の見積もりでは問題なし。

**To Reproduce**
1. トップ画面から見積アップを実施
2. 大黒の原価見積もりを読み込み(数量0、単価0以外のデータを含むものとする)
3. 対象行の単価を確認

**Screenshots**

![image](https://user-images.githubusercontent.com/87287796/213627242-503b9054-7a99-41e9-8613-317f0e37fcc8.png)

**Comment by Lorenzras** [comment]
報告ありがとうございます。

これでは、DBに金額税込みではなく、単価を保存することになります。
ココアスの見積画面でも単価や金額など編集出来るので、対応するのに、そんなに大きい変更でないと思いますが、既存データを更新する必要があります。

**Comment by RPA02coco** [comment]
反応遅くなってすみません。
上記の認識で合っています！

**Comment by Lorenzras** [comment]
修正するPRがマージされましたので、クロースさせて頂きます。
